### ISSUE TITLE
Kademlia Implementation Roadmap

### ISSUE THREAD

**Issue by zixuanzh** [libp2p/py-libp2p#150]
We just landed #129 to work on Kademlia feature by feature. Thanks @zaibon! Here's a summary of what needs to be done in descending order.

- [x] replace (ip, port, node_id) tuple with multiaddr of ip, port, node_id
- [x] implement RoutedHost with Kad DHT
- [x] refactor dial by injecting Router as a dependency
- [x] implement ADD_PROVIDER and REMOVE_PROVIDER
- [ ] implement content routing with Kademlia
- [ ] implement peer discovery by extending content routing as discussed [here](https://github.com/libp2p/py-libp2p/pull/129#issuecomment-468999482) and relevant to #128 
- [ ] phase out rpcudp with gRPC

**Comment by pacrob** [comment]
Closing in favor of #540
