### ISSUE TITLE
Upgrade `gossipsub` to v1.1

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#412]
Spec: https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/README.md

Ref. impl.: https://github.com/libp2p/go-libp2p-pubsub

**Comment by ralexstokes** [comment]
v1.1 spec: https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md

**Comment by mystical-prog** [comment]
@pacrob I will like to work on this issue and make PRs on pragmatic basis

**Comment by mystical-prog** [comment]
As I am working towards upgrading the Gossipsub to V1.1 but along the way I am also trying to fill the gaps in existing v1.0 and Pubsub, for this I am taking reference from go-libp2p and libp2p specs.

### TODOs

- [ ] Implement `seen_ttl` for seen_messages cache in Pubsub Router
- [ ] Add optional `D_LAZY` param coming from gossipsub v1.0

I will keep on updating and adding to this list

**Comment by mystical-prog** [comment]
I have broken down the entire upgrade process into multiple steps -

- [X] Direct Peers
- [x] Peer Exchange & Prune Back Off
- [ ] Activation Function
- [ ] Peer Scoring


Direct Peers PR has been merged and currently I am working towards Peer Exchange & Prune Back Off, while going through the go-libp2p implementation I have found that py-libp2p doesn't have CertifiedAddrBook implementation in PeerStore.

**Comment by seetadev** [comment]
@mystical-prog : Hi Vraj. 

Wish to also share to keep in sync with Gossipsub interop efforts, which are nearing production at https://github.com/libp2p/test-plans/pull/648.  Please also visit https://github.com/ppopth/pubsub-shadow/tree/main .
